package com.farmerbb.notepad.activity;

import java.lang.Exception;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.android.controller.ActivityController;

@RunWith(RobolectricTestRunner.class)
public class CarvedTest_2 {
  @Test
  public void testisShareIntent() throws Exception {
    android.os.Bundle bundle0 = null;
    java.lang.String string0;
    int int0;
    boolean boolean0;
    int int1;
    int int2;
    java.lang.String string1;
    int int3;
    java.lang.String string2;
    int int4;
    int int5;
    android.support.v4.app.DialogFragment dialogfragment0 = null;
    int int6;
    int int7;
    int int8;
    int int9;
    java.lang.String string3;
    android.graphics.drawable.Drawable drawable0 = null;
    int int10;
    java.lang.Class class0;
    java.lang.String string4;
    java.lang.String string5;
    int int11;
    java.util.ArrayList arraylist0 = null;
    android.view.View view0 = null;
    java.lang.Class class1;
    int int12;
    int int13;
    java.lang.String string6;
    int int14;
    android.content.SharedPreferences sharedpreferences0 = null;
    java.lang.Class class2;
    java.lang.String string7;
    java.lang.String string8;
    android.graphics.drawable.Drawable drawable1 = null;
    android.support.v7.app.AlertDialog.Builder builder0 = null;
    android.support.v4.app.DialogFragment dialogfragment1 = null;
    int int15;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem0 = null;
    int int16;
    int int17;
    android.view.View view1 = null;
    int int18;
    java.lang.String string9;
    int int19;
    java.lang.String string10;
    int int20;
    android.app.ActivityManager.TaskDescription taskdescription0 = null;
    int int21;
    int int22;
    android.graphics.Bitmap bitmap0 = null;
    android.support.v4.app.FragmentActivity fragmentactivity0 = null;
    int int23;
    java.lang.String string11;
    int int24;
    int int25;
    java.lang.Class class3;
    java.lang.String string12;
    int int26;
    java.lang.String string13;
    android.widget.ArrayAdapter arrayadapter0 = null;
    int int27;
    int int28;
    int int29;
    java.lang.Class class4;
    int int30;
    android.os.Bundle bundle1 = null;
    int int31;
    java.lang.String string14;
    java.io.File file0 = null;
    int int32;
    android.support.v4.app.Fragment fragment0 = null;
    java.lang.String string15;
    boolean boolean1;
    int int33;
    int int34;
    int int35;
    java.lang.Class class5;
    java.lang.Class class6 = null;
    java.util.List list0 = null;
    int int36;
    java.lang.String string16;
    java.lang.String string17;
    int int37;
    int int38;
    int int39;
    android.support.v4.app.FragmentTransaction fragmenttransaction0 = null;
    android.support.v4.app.FragmentManager fragmentmanager0 = null;
    com.farmerbb.notepad.fragment.dialog.FirstViewDialogFragment firstviewdialogfragment0 = null;
    int int40;
    int int41;
    int int42;
    boolean boolean2;
    android.widget.ArrayAdapter arrayadapter1 = null;
    int int43;
    int int44;
    android.widget.ArrayAdapter arrayadapter2 = null;
    int int45;
    android.os.Bundle bundle2 = null;
    int int46;
    java.util.List list1 = null;
    int int47;
    int int48;
    android.view.View view2 = null;
    boolean boolean3;
    int int49;
    int int50;
    java.lang.String string18;
    java.util.List list2 = null;
    java.lang.String string19;
    int int51;
    java.lang.String string20;
    android.graphics.drawable.Drawable drawable2 = null;
    java.lang.String string21;
    java.lang.Class class7;
    java.lang.String string22;
    android.support.v7.app.AlertDialog.Builder builder1 = null;
    java.lang.String string23;
    java.util.List list3 = null;
    java.lang.String string24;
    int int52;
    int int53;
    int int54;
    java.util.ArrayList arraylist1 = null;
    int int55;
    java.lang.String string25;
    boolean boolean4;
    int int56;
    int int57;
    android.graphics.Bitmap bitmap1 = null;
    java.lang.Class class8;
    android.graphics.drawable.Drawable drawable3 = null;
    android.app.Activity activity0 = null;
    int int58;
    boolean boolean5;
    java.lang.String string26;
    android.widget.ArrayAdapter arrayadapter3 = null;
    com.farmerbb.notepad.activity.MainActivity mainactivity0 = null;
    java.lang.String string27;
    java.lang.String string28;
    int int59;
    int int60;
    int int61;
    java.util.List list4 = null;
    android.graphics.Bitmap bitmap2 = null;
    java.lang.String string29;
    java.lang.Class class9;
    android.graphics.drawable.Drawable drawable4 = null;
    android.widget.ArrayAdapter arrayadapter4 = null;
    java.util.List list5 = null;
    android.view.View view3 = null;
    android.support.v4.app.Fragment fragment1 = null;
    java.lang.String string30;
    boolean boolean6;
    java.lang.String string31;
    android.os.BaseBundle basebundle0 = null;
    int int62;
    android.view.View view4 = null;
    int int63;
    android.app.ActivityManager.TaskDescription taskdescription1 = null;
    int int64;
    java.lang.String string32;
    int int65;
    int int66;
    int int67;
    int int68;
    int int69;
    java.lang.Class class10;
    boolean boolean7;
    java.util.ArrayList arraylist2 = null;
    java.lang.String string33;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem1 = null;
    java.util.ArrayList arraylist3 = null;
    java.lang.String string34;
    java.lang.String string35;
    java.util.List list6 = null;
    android.view.View view5 = null;
    android.os.Bundle bundle3 = null;
    boolean boolean8;
    java.lang.String string36;
    int int70;
    java.util.List list7 = null;
    java.lang.Class class11;
    java.lang.String string37;
    int int71;
    int int72;
    int int73;
    int int74;
    java.lang.Class class12;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem2 = null;
    int int75;
    int int76;
    java.lang.String string38;
    android.view.View view6 = null;
    int int77;
    java.lang.String string39;
    int int78;
    int int79;
    int int80;
    int int81;
    java.lang.String string40;
    java.lang.Class class13;
    android.widget.ArrayAdapter arrayadapter5 = null;
    android.support.v7.app.AppCompatActivity appcompatactivity0 = null;
    int int82;
    int int83;
    int int84;
    int int85;
    int int86;
    android.view.View view7 = null;
    int int87;
    int int88;
    int int89;
    java.util.List list8 = null;
    int int90;
    android.os.Bundle bundle4 = null;
    android.widget.ArrayAdapter arrayadapter6 = null;
    android.graphics.drawable.Drawable drawable5 = null;
    int int91;
    int int92;
    int int93;
    android.support.v4.app.Fragment fragment2 = null;
    com.farmerbb.notepad.fragment.dialog.SaveButtonDialogFragment savebuttondialogfragment0 = null;
    java.lang.String string41;
    int int94;
    int int95;
    boolean boolean9;
    java.lang.String string42;
    int int96;
    java.util.ArrayList arraylist4 = null;
    int int97;
    int int98;
    int int99;
    int int100;
    java.lang.String string43;
    java.lang.Class class14;
    android.support.v4.content.LocalBroadcastManager localbroadcastmanager0 = null;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem3 = null;
    int int101;
    java.lang.Class class15;
    java.util.ArrayList arraylist5 = null;
    android.view.View view8 = null;
    java.lang.String string44;
    java.util.List list9 = null;
    boolean boolean10;
    boolean boolean11;
    java.lang.Class class16;
    java.lang.String string45;
    java.lang.String string46;
    java.lang.String string47;
    int int102;
    android.os.BaseBundle basebundle1 = null;
    java.lang.String string48;
    int int103;
    android.widget.ArrayAdapter arrayadapter7 = null;
    java.lang.String string49;
    java.lang.Class class17;
    java.lang.Class class18;
    int int104;
    int int105;
    android.graphics.drawable.Drawable drawable6 = null;
    android.view.View view9 = null;
    android.os.Bundle bundle5 = null;
    java.lang.String string50;
    java.lang.String string51;
    int int106;
    int int107;
    int int108;
    java.util.List list10 = null;
    android.content.ContextWrapper contextwrapper0 = null;
    android.graphics.Bitmap bitmap3 = null;
    int int109;
    int int110;
    int int111;
    int int112;
    java.util.ArrayList arraylist6 = null;
    int int113;
    java.util.ArrayList arraylist7 = null;
    java.util.ArrayList arraylist8 = null;
    int int114;
    java.lang.String string52;
    java.lang.String string53;
    java.lang.String string54;
    boolean boolean12;
    java.lang.String string55;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem4 = null;
    int int115;
    java.lang.String string56;
    int int116;
    int int117;
    android.app.ActivityManager.TaskDescription taskdescription2 = null;
    int int118;
    boolean boolean13;
    android.support.v7.app.AlertDialog.Builder builder2 = null;
    java.lang.String string57;
    android.widget.ArrayAdapter arrayadapter8 = null;
    int int119;
    android.graphics.drawable.Drawable drawable7 = null;
    int int120;
    boolean boolean14;
    int int121;
    java.lang.Class class19;
    java.lang.String string58;
    int int122;
    java.lang.String string59;
    android.support.v4.app.Fragment fragment3 = null;
    java.lang.Class class20;
    int int123;
    com.farmerbb.notepad.fragment.NoteEditFragment noteeditfragment0 = null;
    java.lang.String string60;
    int int124;
    com.farmerbb.notepad.fragment.NoteEditFragment noteeditfragment1 = null;
    android.support.v4.app.DialogFragment dialogfragment2 = null;
    android.view.View view10 = null;
    boolean boolean15;
    java.lang.Object object0 = null;
    int int125;
    int int126;
    android.view.LayoutInflater layoutinflater0 = null;
    android.widget.ArrayAdapter arrayadapter9 = null;
    int int127;
    int int128;
    java.lang.Class class21;
    java.lang.String string61;
    java.lang.Class class22;
    int int129;
    boolean boolean16;
    int int130;
    java.lang.String string62;
    java.lang.String string63;
    java.lang.String string64;
    android.widget.ArrayAdapter arrayadapter10 = null;
    android.view.GestureDetector gesturedetector0 = null;
    android.content.SharedPreferences sharedpreferences1 = null;
    int int131;
    int int132;
    java.lang.String string65;
    boolean boolean17;
    java.lang.String string66;
    int int133;
    android.content.Intent intent0 = null;
    int int134;
    com.farmerbb.notepad.fragment.NoteViewFragment noteviewfragment0 = null;
    java.lang.String string67;
    java.lang.String string68;
    int int135;
    java.lang.String string69;
    boolean boolean18;
    android.view.View view11 = null;
    com.farmerbb.notepad.fragment.NoteListFragment notelistfragment0 = null;
    int int136;
    java.util.List list11 = null;
    android.widget.ArrayAdapter arrayadapter11 = null;
    int int137;
    int int138;
    com.farmerbb.notepad.fragment.NoteListFragment notelistfragment1 = null;
    int int139;
    android.os.BaseBundle basebundle2 = null;
    java.lang.Class class23;
    int int140;
    java.lang.String string70;
    java.lang.String string71;
    android.os.BaseBundle basebundle3 = null;
    int int141;
    android.os.Bundle bundle6 = null;
    com.farmerbb.notepad.fragment.NoteEditFragment noteeditfragment2 = null;
    int int142;
    int int143;
    int int144;
    int int145;
    int int146;
    boolean boolean19;
    android.app.ActivityManager.TaskDescription taskdescription3 = null;
    int int147;
    int int148;
    int int149;
    java.lang.String string72;
    int int150;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem5 = null;
    int int151;
    java.util.List list12 = null;
    int int152;
    com.farmerbb.notepad.fragment.dialog.FirstRunDialogFragment firstrundialogfragment0 = null;
    java.lang.String string73;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem6 = null;
    java.lang.Class class24;
    java.lang.String string74;
    java.lang.Class class25;
    int int153;
    java.lang.Class class26;
    android.app.ActivityManager.TaskDescription taskdescription4 = null;
    int int154;
    java.lang.String string75;
    int int155;
    int int156;
    android.app.ActivityManager.TaskDescription taskdescription5 = null;
    java.lang.String string76;
    android.support.v4.app.Fragment fragment4 = null;
    android.view.View view12 = null;
    java.lang.String string77;
    android.os.BaseBundle basebundle4 = null;
    java.lang.String string78;
    java.lang.String string79;
    java.lang.String string80;
    int int157;
    int int158;
    android.support.v4.app.FragmentTransaction fragmenttransaction1 = null;
    int int159;
    int int160;
    android.support.v4.app.Fragment fragment5 = null;
    java.lang.String string81;
    int int161;
    java.lang.Class class27;
    java.lang.String string82;
    java.lang.String string83;
    boolean boolean20;
    int int162;
    int int163;
    java.lang.String string84;
    int int164;
    android.widget.ArrayAdapter arrayadapter12 = null;
    java.lang.String string85;
    com.farmerbb.notepad.util.NoteListItem[] notelistitem7 = null;
    int int165;
    int int166;
    android.support.v7.app.ActionBar actionbar0 = null;
    java.lang.String string86;
    int int167;
    android.app.ActivityManager.TaskDescription taskdescription6 = null;
    android.widget.ArrayAdapter arrayadapter13 = null;
    int int168;
    java.lang.String string87;
    int int169;
    android.app.ActivityManager.TaskDescription taskdescription7 = null;
    java.lang.Class class28;
    java.lang.String string88;
    int int170;
    int int171;
    int int172;
    int int173;
    java.util.List list13 = null;
    com.farmerbb.notepad.fragment.NoteViewFragment.2 20 = null;
    android.support.v4.app.FragmentManagerImpl fragmentmanagerimpl0 = null;
    int int174;
    android.widget.ArrayAdapter arrayadapter14 = null;
    int int175;
    android.content.Context context0 = null;
    java.util.List list14 = null;
    int int176;
    android.widget.ArrayAdapter arrayadapter15 = null;
    int int177;
    android.view.View view13 = null;
    java.lang.String string89;
    android.view.View view14 = null;
    android.view.View view15 = null;
    java.lang.String string90;
    int int178;
    int int179;
    int int180;
    int int181;
    java.util.List list15 = null;
    android.view.View view16 = null;
    java.lang.String string91;
    java.lang.Class class29;
    java.lang.String string92;
    android.view.View view17 = null;
    java.lang.String string93;
    int int182;
    int int183;
    int int184;
    java.lang.String string94;
    java.lang.String string95;
    android.support.v4.app.FragmentTransaction fragmenttransaction2 = null;
    notelistitem4 = org.mockito.Mockito.mock(com.farmerbb.notepad.util.NoteListItem[].class);
    ActivityController<MainActivity> activityController = Robolectric.buildActivity(MainActivity.class);
    mainactivity0 = activityController.get();
    activityController.null(bundle1);
    activityController.null();
    activityController.null(bundle3);
    activityController.null();
    sharedpreferences1 = activity0.getPreferences(0);
    string64 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int81 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099790);
    int43 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099790);
    view13 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist7 = new ArrayList(0);
    list1 = java.util.Arrays.asList(notelistitem6);
    boolean15 = arraylist7.addAll(list12);
    arrayadapter13 = new ArrayAdapter(mainactivity0,2131492932,arraylist7);
    arrayadapter9 = new ArrayAdapter(mainactivity0,2131492931,arraylist7);
    arraylist6 = mainactivity0.getCabArray();
    view7 = activity0.findViewById(2131296331);
    sharedpreferences1 = activity0.getPreferences(0);
    activity0.setTitle("Notepad");
    drawable0 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int2 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription4 = new TaskDescription("Notepad",bitmap3,-16737844);
    activity0.setTaskDescription(taskdescription4);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    actionbar0 = appcompatactivity0.getSupportActionBar();
    string29 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int44 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099790);
    int7 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099790);
    view13 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist3 = new ArrayList(0);
    list5 = java.util.Arrays.asList(notelistitem3);
    boolean12 = arraylist3.addAll(list7);
    arrayadapter10 = new ArrayAdapter(mainactivity0,2131492932,arraylist3);
    arrayadapter11 = new ArrayAdapter(mainactivity0,2131492931,arraylist3);
    arraylist6 = mainactivity0.getCabArray();
    view7 = activity0.findViewById(2131296331);
    mainactivity0.onFirstRunDialogPositiveClick();
    intent0 = new Intent(mainactivity0,class6);
    activityController.null();
    activityController.null();
    sharedpreferences1 = activity0.getPreferences(0);
    string56 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int101 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int35 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    view13 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist0 = new ArrayList(0);
    list6 = java.util.Arrays.asList(notelistitem7);
    boolean10 = arraylist0.addAll(list3);
    arrayadapter5 = new ArrayAdapter(mainactivity0,2131492932,arraylist0);
    arrayadapter8 = new ArrayAdapter(mainactivity0,2131492931,arraylist0);
    arraylist6 = mainactivity0.getCabArray();
    view7 = activity0.findViewById(2131296331);
    sharedpreferences1 = activity0.getPreferences(0);
    activity0.setTitle("Notepad");
    drawable6 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int54 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription1 = new TaskDescription("Notepad",bitmap2,-16737844);
    activity0.setTaskDescription(taskdescription1);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    actionbar0 = appcompatactivity0.getSupportActionBar();
    string68 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int34 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int162 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    view13 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist8 = new ArrayList(0);
    list4 = java.util.Arrays.asList(notelistitem0);
    boolean16 = arraylist8.addAll(list14);
    arrayadapter2 = new ArrayAdapter(mainactivity0,2131492932,arraylist8);
    arrayadapter14 = new ArrayAdapter(mainactivity0,2131492931,arraylist8);
    arraylist6 = mainactivity0.getCabArray();
    view7 = activity0.findViewById(2131296331);
    mainactivity0.startMultiSelect();
    arraylist6 = mainactivity0.getCabArray();
    bundle6 = new Bundle();
    basebundle3.putString("filename","new");
    noteeditfragment2 = new NoteEditFragment();
    fragment5.setArguments(bundle6);
    fragmenttransaction0 = fragmentmanager0.beginTransaction();
    fragmenttransaction0 = fragmenttransaction0.replace(2131296386,noteeditfragment2,"NoteEditFragment");
    noteeditfragment2.onAttach(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    view5 = activity0.findViewById(2131296359);
    view16 = activity0.findViewById(2131296329);
    string45 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view11 = activity0.findViewById(2131296409);
    int118 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    int87 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int26 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    object0 = activity0.getSystemService("input_method");
    boolean8 = mainactivity0.isShareIntent();
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    sharedpreferences1 = activity0.getPreferences(0);
    boolean17 = mainactivity0.isShareIntent();
    activity0.setTitle("New Note");
    drawable2 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int95 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription7 = new TaskDescription("New Note",bitmap2,-16737844);
    activity0.setTaskDescription(taskdescription7);
    string31 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    boolean2 = mainactivity0.isShareIntent();
    object0 = activity0.getSystemService("input_method");
    view16 = activity0.findViewById(2131296329);
    view16 = activity0.findViewById(2131296329);
    string86 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    mainactivity0.showSaveButtonDialog();
    savebuttondialogfragment0.onAttach(mainactivity0);
    builder0 = new Builder(mainactivity0);
    mainactivity0.onSaveDialogPositiveClick();
    file0 = contextwrapper0.getFilesDir();
    arraylist1 = new ArrayList(1);
    string17 = mainactivity0.loadNoteTitle("1554121069869");
    string6 = mainactivity0.loadNoteDate("1554121069869");
    list8 = java.util.Arrays.asList(notelistitem5);
    boolean5 = arraylist1.addAll(list9);
    arrayadapter1 = new ArrayAdapter(mainactivity0,2131492932,arraylist1);
    arrayadapter3 = new ArrayAdapter(mainactivity0,2131492931,arraylist1);
    arraylist6 = mainactivity0.getCabArray();
    noteviewfragment0.onAttach(mainactivity0);
    boolean4 = mainactivity0.isShareIntent();
    boolean7 = mainactivity0.isShareIntent();
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    string61 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    string39 = mainactivity0.loadNoteTitle("1554121069869");
    activity0.setTitle("Tretewrew");
    drawable3 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int107 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription5 = new TaskDescription("Tretewrew",bitmap1,-16737844);
    activity0.setTaskDescription(taskdescription5);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    view5 = activity0.findViewById(2131296359);
    view2 = activity0.findViewById(2131296451);
    view1 = activity0.findViewById(2131296370);
    string53 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view9 = activity0.findViewById(2131296408);
    int140 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    int119 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int59 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    string74 = mainactivity0.loadNote("1554121069869");
    sharedpreferences1 = activity0.getPreferences(0);
    firstviewdialogfragment0 = new FirstViewDialogFragment();
    dialogfragment0.show(fragmentmanagerimpl0,"firstloadfragment");
    gesturedetector0 = new GestureDetector(mainactivity0,20);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    builder2 = new Builder(mainactivity0);
    fragmentactivity0.onBackPressed();
    notelistfragment1.onAttach(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    view6 = activity0.findViewById(2131296303);
    view5 = activity0.findViewById(2131296359);
    sharedpreferences1 = activity0.getPreferences(0);
    sharedpreferences1 = activity0.getPreferences(0);
    activity0.setTitle("Notepad");
    drawable4 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int181 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription6 = new TaskDescription("Notepad",bitmap1,-16737844);
    activity0.setTaskDescription(taskdescription6);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    actionbar0 = appcompatactivity0.getSupportActionBar();
    string93 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int68 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int8 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    view17 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist2 = new ArrayList(1);
    string83 = mainactivity0.loadNoteTitle("1554121069869");
    string18 = mainactivity0.loadNoteDate("1554121069869");
    list2 = java.util.Arrays.asList(notelistitem2);
    boolean9 = arraylist2.addAll(list0);
    arrayadapter0 = new ArrayAdapter(mainactivity0,2131492932,arraylist2);
    arrayadapter4 = new ArrayAdapter(mainactivity0,2131492931,arraylist2);
    arraylist6 = mainactivity0.getCabArray();
    layoutinflater0 = android.view.LayoutInflater.'from'(mainactivity0);
    string24 = context0.getPackageName();
    sharedpreferences0 = context0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    int45 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    arraylist6 = mainactivity0.getCabArray();
    bundle2 = new Bundle();
    basebundle2.putString("filename","new");
    noteeditfragment0 = new NoteEditFragment();
    fragment1.setArguments(bundle2);
    fragmenttransaction2 = fragmentmanager0.beginTransaction();
    fragmenttransaction2 = fragmenttransaction2.replace(2131296386,noteeditfragment0,"NoteEditFragment");
    noteeditfragment0.onAttach(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    view5 = activity0.findViewById(2131296359);
    view4 = activity0.findViewById(2131296329);
    string15 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view15 = activity0.findViewById(2131296409);
    int16 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    int42 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int166 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    object0 = activity0.getSystemService("input_method");
    boolean19 = mainactivity0.isShareIntent();
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    sharedpreferences1 = activity0.getPreferences(0);
    boolean0 = mainactivity0.isShareIntent();
    activity0.setTitle("New Note");
    drawable1 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int115 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription3 = new TaskDescription("New Note",bitmap1,-16737844);
    activity0.setTaskDescription(taskdescription3);
    string19 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    boolean13 = mainactivity0.isShareIntent();
    object0 = activity0.getSystemService("input_method");
    view4 = activity0.findViewById(2131296329);
    fragmentactivity0.onBackPressed();
    fragment0.onAttach(mainactivity0);
    builder1 = new Builder(mainactivity0);
    mainactivity0.onBackDialogPositiveClick(null);
    file0 = contextwrapper0.getFilesDir();
    arraylist5 = new ArrayList(2);
    string12 = mainactivity0.loadNoteTitle("1554121077872");
    string57 = mainactivity0.loadNoteDate("1554121077872");
    string54 = mainactivity0.loadNoteTitle("1554121069869");
    string42 = mainactivity0.loadNoteDate("1554121069869");
    list11 = java.util.Arrays.asList(notelistitem1);
    boolean3 = arraylist5.addAll(list10);
    arrayadapter15 = new ArrayAdapter(mainactivity0,2131492932,arraylist5);
    arrayadapter6 = new ArrayAdapter(mainactivity0,2131492931,arraylist5);
    arraylist6 = mainactivity0.getCabArray();
    notelistfragment0.onAttach(mainactivity0);
    boolean11 = mainactivity0.isShareIntent();
    boolean14 = mainactivity0.isShareIntent();
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    view0 = activity0.findViewById(2131296303);
    view5 = activity0.findViewById(2131296359);
    sharedpreferences1 = activity0.getPreferences(0);
    sharedpreferences1 = activity0.getPreferences(0);
    activity0.setTitle("Notepad");
    drawable7 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int135 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription2 = new TaskDescription("Notepad",bitmap0,-16737844);
    activity0.setTaskDescription(taskdescription2);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    actionbar0 = appcompatactivity0.getSupportActionBar();
    string22 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view8 = activity0.findViewById(2131296386);
    view10 = activity0.findViewById(2131296384);
    int120 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int58 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    view14 = activity0.findViewById(2131296368);
    file0 = contextwrapper0.getFilesDir();
    arraylist4 = new ArrayList(2);
    string77 = mainactivity0.loadNoteTitle("1554121077872");
    string14 = mainactivity0.loadNoteDate("1554121077872");
    string23 = mainactivity0.loadNoteTitle("1554121069869");
    string2 = mainactivity0.loadNoteDate("1554121069869");
    list15 = java.util.Arrays.asList(notelistitem4);
    boolean6 = arraylist4.addAll(list13);
    arrayadapter12 = new ArrayAdapter(mainactivity0,2131492932,arraylist4);
    arrayadapter7 = new ArrayAdapter(mainactivity0,2131492931,arraylist4);
    arraylist6 = mainactivity0.getCabArray();
    layoutinflater0 = android.view.LayoutInflater.'from'(mainactivity0);
    string1 = context0.getPackageName();
    sharedpreferences0 = context0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    int153 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    layoutinflater0 = android.view.LayoutInflater.'from'(mainactivity0);
    string82 = context0.getPackageName();
    sharedpreferences0 = context0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    int18 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    arraylist6 = mainactivity0.getCabArray();
    bundle0 = new Bundle();
    basebundle4.putString("filename","new");
    noteeditfragment1 = new NoteEditFragment();
    fragment4.setArguments(bundle0);
    fragmenttransaction1 = fragmenttransaction1.replace(2131296386,noteeditfragment1,"NoteEditFragment");
    noteeditfragment1.onAttach(mainactivity0);
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    actionbar0 = appcompatactivity0.getSupportActionBar();
    view5 = activity0.findViewById(2131296359);
    view12 = activity0.findViewById(2131296329);
    string90 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    view3 = activity0.findViewById(2131296409);
    int94 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099785);
    int173 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    int108 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099791);
    object0 = activity0.getSystemService("input_method");
    boolean20 = mainactivity0.isShareIntent();
    localbroadcastmanager0 = android.support.v4.content.LocalBroadcastManager.getInstance(mainactivity0);
    sharedpreferences1 = activity0.getPreferences(0);
    boolean1 = mainactivity0.isShareIntent();
    activity0.setTitle("New Note");
    drawable5 = android.support.v4.content.ContextCompat.getDrawable(mainactivity0,2131230830);
    int178 = android.support.v4.content.ContextCompat.getColor(mainactivity0,2131099761);
    taskdescription0 = new TaskDescription("New Note",bitmap0,-16737844);
    activity0.setTaskDescription(taskdescription0);
    string73 = contextwrapper0.getPackageName();
    sharedpreferences0 = contextwrapper0.getSharedPreferences("com.farmerbb.notepad_preferences",0);
    boolean18 = mainactivity0.isShareIntent();
  }
}

