language: android
jdk: oraclejdk8
sudo: false

env:
  matrix:
    - ANDROID_TARGET=android-29
  global:
    - GRADLE_OPTS="-Xms128m"

android:
  components:
    # needed build tools
    - build-tools-29.0.2

    # The SDK version used to compile your project
    - android-29

    # extra needed components
    - extra-android-m2repository

before_script:

script: 
  - ./gradlew assembleRelease lintRelease testDebugUnitTest 
